#!/usr/bin/env python3
import sys
import subprocess

def execute_commands_from_file(mode):
    file_name = f"{mode}.mode"
    try:
        with open(file_name, "r") as file:
            for line in file:
                command = line.strip()
                command = f'swaymsg "{command}"'
                if command:
                    print(f"Executing: {command}")
                    subprocess.run([f"{command}"], shell=True)
    except FileNotFoundError:
        print(f"Error: File '{file_name}' not found.")

def read_current_file():
    try:
        with open("current", "r") as file:
            for line in file:
                mode = line.strip()
                if mode:
                    print(mode)
    except FileNotFoundError:
        print("Error: File 'current' not found.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        read_current_file()
    else:
        mode = sys.argv[1]
        with open("current", "w") as file:
            file.write(mode)

        execute_commands_from_file(mode)

