# import variables into system-user environment
# See https://wiki.archlinux.org/title/XDG_Desktop_Portal for details

exec = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP

exec = hash dbus-update-activation-environment 2>/dev/null && dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=hyprland

# Hyprland on Ubuntu does not start a graphical session, do so
exec-once = systemctl --user start graphical-session.target
