###########################
### LOCAL MONITOR SETUP ###
###########################

# https://wiki.hypr.land/Configuring/Monitors/ for more information

# Display variable assignment
$primaryMonitor = eDP-1
$secondaryMonitor = eDP-1
$tertiaryMonitor = eDP-1

# Monitor positioning - triple monitor setup
#monitor = $secondaryMonitor, 3840x2160@120, 0x0, 1
#monitor = $primaryMonitor, 3840x2160@120, 3840x0, 1
#monitor = $tertiaryMonitor, 3840x2160@120, 7680x0, 1

