##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Workspace to monitor assignment
workspace = 1, monitor:$primaryMonitor

## default: true ensures the affinity but does not create the workspaces
workspace = 2, monitor:$primaryMonitor, default: true
workspace = 3, monitor:$primaryMonitor, default: true

## Secondary assignment
workspace = 5, defaultName:chat, monitor:$secondaryMonitor, on-created-empty:$chat

## Tertiary assignment
workspace = 4, defaultName:meet, monitor:$tertiaryMonitor, on-created-empty:$meet
workspace = 6, monitor:$tertiaryMonitor, default: true
