# focus window color (border)
general {
    col.active_border = rgb(71CEAD)
}

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(FF6B6B)
}

# Groupbar tabs match the waybar colors
$groupBarBackground = rgb(11221C)
$groupBarText = rgb(e6d8ba)
