#!/bin/zsh
#
# GRUB menu: readable font size, centered list, Windows second. Optional -
# toggle the `grub` feature via `dot config`.

source $HOME/src/config/install/common.sh

# Nothing to do on a non-GRUB machine (macOS, or an EFI-stub/systemd-boot box).
if [[ "$OSTYPE" != "linux-gnu"* ]] || ! type grub-mkconfig > /dev/null 2>&1
then
    exit 0
fi

theme_dir=/boot/grub/themes/ristretto
dropin=/etc/default/grub.d/99-dotfiles.cfg
generator=/etc/grub.d/11_linux_windows
ttf=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf

# Set when something actually changed on disk, so update-grub - which is slow
# and rewrites the boot config - only runs when there's a reason to.
changed=0

# Copy only when the destination is missing or differs.
sync_file()
{
    if ! cmp -s "$1" "$2"
    then
        sudo cp "$1" "$2"
        changed=1
    fi
}

if ! feature_enabled grub
then
    # Turning the feature off has to undo the install, not just skip it -
    # otherwise 10_linux stays disabled and the menu is generated by a
    # generator we no longer manage.
    if [ -e "$generator" ] || [ -e "$dropin" ] || [ -d "$theme_dir" ]
    then
        print_note " -- Reverting GRUB menu to stock"
        sudo rm -f $generator $dropin
        sudo rm -rf $theme_dir
        sudo chmod +x /etc/grub.d/10_linux /etc/grub.d/30_os-prober
        sudo update-grub
    fi
    exit 0
fi

# GRUB renders .pf2 bitmaps at a fixed size and never scales them, so the only
# way to get readable text on a hidpi panel is to bake the font at the size we
# want. 00_header auto-emits `loadfont` for every .pf2 in the theme directory,
# so they just need to land there. grub-mkfont names them "<family> Regular
# <size>", which is what theme.txt references.
[ -d "$theme_dir" ] || sudo mkdir -p $theme_dir
for size in 20 32
do
    font=$theme_dir/dejavu-mono-$size.pf2
    if [ ! -f "$font" ]
    then
        print_note " -- Building GRUB font at ${size}px"
        sudo grub-mkfont -s $size -o $font $ttf
        changed=1
    fi
done

sync_file $SRC_ROOT/grub/theme.txt $theme_dir/theme.txt
sync_file $SRC_ROOT/grub/99-dotfiles.cfg $dropin
sync_file $SRC_ROOT/grub/11_linux_windows $generator
[ -x "$generator" ] || { sudo chmod +x $generator; changed=1 }

# 11_linux_windows runs both stock generators itself, so they must not also run
# on their own. See grub/11_linux_windows for why numbering alone can't put
# Windows second. Both are dpkg conffiles, so a grub-common upgrade can restore
# the exec bit - this re-disables them on the next run.
for stock in /etc/grub.d/10_linux /etc/grub.d/30_os-prober
do
    if [ -x "$stock" ]
    then
        sudo chmod -x $stock
        changed=1
    fi
done

if [ $changed -eq 1 ]
then
    print_note " -- Configuring GRUB menu"
    sudo update-grub
fi
