general {
    col.active_border = rgb(a89984)
}

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(cc241d)
}

# Groupbar tabs match the waybar colors
$groupBarBackground = rgb(282828)
$groupBarText = rgb(d4be98)
