general {
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgb(e6d9db)
}

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(c7a0a5)
}

# Groupbar tabs match the waybar colors
$groupBarBackground = rgb(2c2525)
$groupBarText = rgb(e6d9db)
