general {
    col.active_border = rgb(575279)
}

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(eb6f92)
}

# Groupbar tabs match the waybar colors
$groupBarBackground = rgb(faf4ed)
$groupBarText = rgb(575279)
