##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule (block syntax, Hyprland 0.53+)
# windowrule {
#     match:class = ^(kitty)$
#     match:title = ^(kitty)$
#     float = true
# }

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Default workspace names
workspace = 1, on-created-empty:$terminal
workspace = 4, defaultName:meet
workspace = 5, defaultName:chat
