general {
    col.active_border = rgb(d3c6aa)
}

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(e67e80)
}

# Groupbar tabs match the waybar colors
$groupBarBackground = rgb(2d353b)
$groupBarText = rgb(d3c6aa)
